# To use this file, insall the REST Client extension
# vscode:extension/humao.rest-client

# To switch environments:
#  - Ctrl+Alt+E(Cmd+Alt+E for macOS)
#  - Or `Rest Client: Switch Environment` from command palette

# You'll need to switch to either `local` or `vercel` to get started.

@baseUrl = {{host}}/api/event
GET {{baseUrl}}
###

GET  {{baseUrl}}

###

POST {{baseUrl}}
Content-Type: application/json

{
    "hostName": "jack",
    "Street": "Care Facts",
    "city": "over there",
    "date": 202020,
    "time": 1520,
    "info": "bring a hat",
    "notInvited": [
      "cats"
    ]
  }
###
PATCH {{baseUrl}}/timmy
Content-Type: application/json

{
 
    "Street": "another one"
}
###

DELETE {{baseUrl}}/timmy
###
@evendid = 63fd00a59ba8f0f463ef0a28
@guestid =  63fd00a69ba8f0f463ef0a2c
PATCH  {{baseUrl}}/{{evendid}}/{{guestid}}
###
PATCH  {{baseUrl}}/d/{{evendid}}/{{guestid}}
###
@guesturl = {{host}}/api/guest
POST {{guesturl}}
Content-Type: application/json

{
  "name": "mark",
  "food": ["chips"],
  "drink": ["soda"],
  "plusOne": false,
  "canDJ": false

}

###
PATCH {{baseUrl}}guest/Tim
Content-Type: application/json

{
 
    "name": "Tim the second"
}

###

DELETE {{guesturl}}/antony